### ISSUE TITLE
Cannot disable the plugin in test env.

### ISSUE THREAD

**Issue by jglapa** [agorapulse/grails-sentry#50] opened 2019-04-23 14:55 UTC
I cannot disable the plugin in `test`  environment. 
After looking a bit closer it seems that the plugin jar contains  `application-test.yml` config file which is overriding the config in `test` env

I've inspected the 2 most recent versions `v11.6.5` and `v11.7.4` and both have that file included.

**Comment by musketyr** [comment] 2019-04-25 13:24
I've checked the jars from the Bintray repository and none of the recent JARs contained `application-test.yml`. can you attach the JAR files having the files as you mentioned?

**Comment by jglapa** [comment] 2019-04-25 18:26
oh, I see now on bintray that there are more versions than listed on the repo landing side:
```
11.7.5.2
11.7.5.1
11.7.5
11.7.4
11.7.3
11.6.5
```

I've check only `11.6.5` and `11.7.4` and both had that file. 

It appears that the file disappeared from version > `11.7.4` but I cannot use it:( I'm getting:

```
Caused by: org.grails.core.exceptions.GrailsRuntimeException: Failed to introspect class: class grails.plugin.sentry.Application
	at grails.core.ArtefactHandlerAdapter.isArtefact(ArtefactHandlerAdapter.java:129)
	at grails.core.DefaultGrailsApplication.addOverridableArtefact(DefaultGrailsApplication.java:772)
	at org.grails.plugins.AbstractGrailsPluginManager.registerProvidedArtefacts(AbstractGrailsPluginManager.java:310)
	at grails.boot.config.GrailsApplicationPostProcessor.performGrailsInitializationSequence(GrailsApplicationPostProcessor.groovy:110)
	at grails.boot.config.GrailsApplicationPostProcessor.initializeGrailsApplication(GrailsApplicationPostProcessor.groovy:93)
	at grails.boot.config.GrailsApplicationPostProcessor.setApplicationContext(GrailsApplicationPostProcessor.groovy:225)
	at grails.boot.config.GrailsApplicationPostProcessor.<init>(GrailsApplicationPostProcessor.groovy:77)
	at grails.boot.config.GrailsAutoConfiguration.grailsApplicationPostProcessor(GrailsAutoConfiguration.groovy:68)
	at adverity.Application.grailsApplicationPostProcessor(Application.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 24 common frames omitted
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
```
Most likely grails incompatibility. 
I'm still using`3.2.6`.

I think the only way around this is to create an `application-test.yml` file in `conf/` and disable the plugin there.. Should give it a higher priority.

Yep, seems it did the trick.

**Comment by musketyr** [comment] 2019-04-26 06:31
I'm glad to hear that you've found a solution which works for you. So the original problem is fixed in the latest releases. I'm sorry but this probably caused by Grails being heavily depending on traits which implementation changes from time to time. 

I'm closing this issue as the original problem is no longer present.

**Closed by musketyr** 2019-04-26 06:31 UTC
